<?php

namespace Teksite\Handler\Tests\Feature;

use Illuminate\Http\Request;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use InvalidArgumentException;
use PHPUnit\Framework\Attributes\Test;
use Teksite\Handler\Contracts\FetchDataContract;
use Teksite\Handler\Facade\FetchData;
use Teksite\Handler\Services\FetchDataService;
use Teksite\Handler\Tests\Fixtures\Models\Post;
use Teksite\Handler\Tests\Fixtures\Models\User;
use Teksite\Handler\Tests\TestCase;

class FetchDataServiceTest extends TestCase
{
    private function withQuery(array $query): FetchDataService
    {
        $this->app->instance('request', Request::create('/', 'GET', $query));

        return $this->app->make(FetchDataContract::class);
    }

    /**
     * @return array<int, string>
     */
    private function capturedQueries(\Closure $callback): array
    {
        $queries = [];

        DB::listen(function ($event) use (&$queries) {
            $sql = strtolower(trim($event->sql));

            /*
             * SQLite may execute internal schema/metadata queries while
             * Laravel inspects table columns. These are not the query
             * generated by FetchData that these tests need to assert.
             */
            if (
                str_contains($sql, 'pragma_')
                || str_contains($sql, 'sqlite_master')
                || str_contains($sql, 'sqlite_schema')
            ) {
                return;
            }

            $queries[] = $event->sql;
        });

        $callback();

        return $queries;
    }

    private function mainSelect(array $queries): string
    {
        foreach ($queries as $query) {
            $normalized = strtolower(trim($query));

            if (
                str_starts_with($normalized, 'select')
                && !str_contains($normalized, 'count(')
            ) {
                return $query;
            }
        }

        return '';
    }

    #[Test]
    public function get_actually_returns_the_fetched_records_instead_of_the_service_instance(): void
    {
        $user = User::create(['name' => 'Ada']);
        Post::create(['user_id' => $user->id, 'title' => 'Hello world']);

        $result = FetchData::get(Post::class);

        $this->assertInstanceOf(LengthAwarePaginator::class, $result);
        $this->assertSame(1, $result->total());
        $this->assertSame('Hello world', $result->first()->title);
    }

    #[Test]
    public function per_page_false_returns_a_plain_collection_instead_of_a_paginator(): void
    {
        $user = User::create(['name' => 'Ada']);
        collect(range(1, 3))->each(
            fn ($i) => Post::create([
                'user_id' => $user->id,
                'title' => "Post {$i}",
            ])
        );

        $result = FetchData::perPage(false)->get(Post::class);

        $this->assertInstanceOf(Collection::class, $result);
        $this->assertCount(3, $result);
    }

    #[Test]
    public function only_stays_fluent_and_restricts_the_selected_columns(): void
    {
        $user = User::create(['name' => 'Ada']);

        Post::create([
            'user_id' => $user->id,
            'title' => 'Hello world',
            'category' => 'news',
        ]);

        $sql = $this->mainSelect(
            $this->capturedQueries(function () {
                FetchData::only(['title'])->get(Post::class);
            })
        );

        $this->assertStringContainsString('select "title", "id"', $sql);
        $this->assertStringNotContainsString('"category"', $sql);
    }

    #[Test]
    public function search_filters_records_using_a_like_condition_on_the_configured_input(): void
    {
        $user = User::create(['name' => 'Ada']);

        Post::create([
            'user_id' => $user->id,
            'title' => 'Laravel tips',
        ]);

        Post::create([
            'user_id' => $user->id,
            'title' => 'Cooking recipes',
        ]);

        $result = $this->withQuery(['s' => 'laravel'])
                       ->search(['title'])
                       ->get(Post::class);

        $this->assertSame(1, $result->total());
        $this->assertSame('Laravel tips', $result->first()->title);
    }

    #[Test]
    public function search_supports_filtering_through_a_relation(): void
    {
        $ada = User::create(['name' => 'Ada Lovelace']);
        $grace = User::create(['name' => 'Grace Hopper']);

        Post::create([
            'user_id' => $ada->id,
            'title' => 'Post by Ada',
        ]);

        Post::create([
            'user_id' => $grace->id,
            'title' => 'Post by Grace',
        ]);

        $result = $this->withQuery(['s' => 'Grace'])
                       ->search(['user.name'])
                       ->get(Post::class);

        $this->assertSame(1, $result->total());
        $this->assertSame('Post by Grace', $result->first()->title);
    }

    #[Test]
    public function order_by_and_sort_can_be_set_fluently(): void
    {
        $user = User::create(['name' => 'Ada']);

        Post::create([
            'user_id' => $user->id,
            'title' => 'Banana',
        ]);

        Post::create([
            'user_id' => $user->id,
            'title' => 'Apple',
        ]);

        $result = FetchData::orderBy('title')
                           ->sort('asc')
                           ->get(Post::class);

        $this->assertSame('Apple', $result->first()->title);
    }

    #[Test]
    public function order_by_falls_back_to_the_request_query_parameters_when_not_set_fluently(): void
    {
        $user = User::create(['name' => 'Ada']);

        Post::create([
            'user_id' => $user->id,
            'title' => 'Banana',
        ]);

        Post::create([
            'user_id' => $user->id,
            'title' => 'Apple',
        ]);

        $result = $this->withQuery([
            'order' => 'title',
            'sort' => 'asc',
        ])->get(Post::class);

        $this->assertSame('Apple', $result->first()->title);
    }

    #[Test]
    public function order_by_ignores_relation_paths_and_unknown_columns_coming_from_the_request(): void
    {
        $user = User::create(['name' => 'Ada']);

        Post::create([
            'user_id' => $user->id,
            'title' => 'Old post',
            'created_at' => now()->subDay(),
        ]);

        Post::create([
            'user_id' => $user->id,
            'title' => 'New post',
            'created_at' => now(),
        ]);

        // "user.name" is a relation path and "not_a_real_column" doesn't
        // exist - both should be rejected in favour of the configured
        // default ("created_at desc").
        $byRelation = $this->withQuery([
            'order' => 'user.name',
        ])->get(Post::class);

        $this->assertSame('New post', $byRelation->first()->title);

        $byUnknownColumn = $this->withQuery([
            'order' => 'not_a_real_column',
        ])->get(Post::class);

        $this->assertSame('New post', $byUnknownColumn->first()->title);
    }

    #[Test]
    public function limit_pagination_caps_the_effective_per_page_value(): void
    {
        $user = User::create(['name' => 'Ada']);

        collect(range(1, 5))->each(
            fn ($i) => Post::create([
                'user_id' => $user->id,
                'title' => "Post {$i}",
            ])
        );

        $result = FetchData::perPage(10)
                           ->limitPagination(2)
                           ->get(Post::class);

        $this->assertSame(2, $result->perPage());
    }

    #[Test]
    public function limit_pagination_false_removes_the_cap(): void
    {
        $user = User::create(['name' => 'Ada']);

        collect(range(1, 5))->each(
            fn ($i) => Post::create([
                'user_id' => $user->id,
                'title' => "Post {$i}",
            ])
        );

        $result = FetchData::perPage(5)
                           ->limitPagination(false)
                           ->get(Post::class);

        $this->assertSame(5, $result->perPage());
        $this->assertSame(5, $result->total());
    }

    #[Test]
    public function reset_clears_previously_configured_fluent_state(): void
    {
        $service = $this->withQuery([]);

        $user = User::create(['name' => 'Ada']);

        Post::create([
            'user_id' => $user->id,
            'title' => 'Keep me',
            'category' => 'news',
        ]);

        $queries = $this->capturedQueries(function () use ($service) {
            $service
                ->only(['title'])
                ->reset()
                ->get(Post::class);
        });

        // After reset(), only() should no longer be in effect, so every
        // column is selected again.
        $this->assertStringContainsString(
            'select *',
            $this->mainSelect($queries)
        );
    }

    #[Test]
    public function it_throws_for_a_class_that_does_not_extend_eloquent_model(): void
    {
        $this->expectException(InvalidArgumentException::class);

        FetchData::get(\stdClass::class);
    }

    #[Test]
    public function it_throws_for_an_unsupported_model_argument(): void
    {
        $this->expectException(InvalidArgumentException::class);

        FetchData::get(42);
    }

    #[Test]
    public function forget_columns_cache_clears_the_cache_for_a_single_model(): void
    {
        // Trigger a query so the "posts" column listing gets cached.
        FetchData::get(Post::class);

        $this->assertTrue(
            Cache::has('fetch-data-columns:default:posts')
        );

        FetchData::forgetColumnsCache(Post::class);

        $this->assertFalse(
            Cache::has('fetch-data-columns:default:posts')
        );
    }
}
